/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managerrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.ManagerOrganization;
import business.organization.Organization;
import business.organization.PlayerOrganization;
import business.role.PlayerRole;
import business.role.Role;
import business.useraccount.UserAccount;
import business.workqueue.BossToManagerWorkRequest;
import business.workqueue.ContractWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mwhai_000
 */
public class ReceiveTransferContract extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private ManagerOrganization managerOrganization;
    private EcoSystem system;

    /**
     * Creates new form CreateContract
     */
    ReceiveTransferContract(JPanel userProcessContainer, UserAccount userAccount, ManagerOrganization managerOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.managerOrganization = managerOrganization;
        this.system = system;
        populatePlayerTable();
    }

    public void populatePlayerTable() {
        DefaultTableModel model = (DefaultTableModel) playerJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : managerOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ContractWorkRequest) {
                if (!((ContractWorkRequest) request).getBuyer().equals(enterprise)) {
                    Object[] row = new Object[3];
                    row[0] = (ContractWorkRequest) request;
                    row[1] = ((ContractWorkRequest) request).getSeller();
                    row[2] = ((ContractWorkRequest) request).getSignOnFee();
                    model.addRow(row);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgree = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblSignOnFee = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblBuyerClub = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblWage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblSellerClub = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDeclineContract = new javax.swing.JButton();
        btnAViewDetail = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        btnAgree.setText("Agree & Send to Player");
        btnAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreeActionPerformed(evt);
            }
        });

        playerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player Name", "Seller", "Transfer Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(playerJTable);
        if (playerJTable.getColumnModel().getColumnCount() > 0) {
            playerJTable.getColumnModel().getColumn(0).setResizable(false);
            playerJTable.getColumnModel().getColumn(1).setResizable(false);
            playerJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel11.setText("Receive Transfer Contract");

        lblSignOnFee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSignOnFee.setText("<SignOnFee>");

        lblBonus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBonus.setText("<Bonus>");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Bonus:");

        lblBuyerClub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBuyerClub.setText("<Enterprise>");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Wage:");

        lblWage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWage.setText("<Wage>");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Transfer Fee:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Transfer Contract");

        lblDuration.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDuration.setText("<Duration>");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Player");

        lblPlayerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPlayerName.setText("<PlayerName>");

        lblSellerClub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSellerClub.setText("<Enterprise>");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Bewteen");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("and");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Duration:");

        btnDeclineContract.setText("Decline");
        btnDeclineContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineContractActionPerformed(evt);
            }
        });

        btnAViewDetail.setText("View Detail");
        btnAViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAViewDetailActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("End Date:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Start Date:");

        lblStartDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblStartDate.setText("<StartDate>");

        lblEndDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEndDate.setText("<Duration>");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 190, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAViewDetail)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayerName)
                            .addComponent(lblWage)
                            .addComponent(lblSignOnFee)
                            .addComponent(lblBonus)
                            .addComponent(lblDuration)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSellerClub)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(lblBuyerClub))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStartDate)
                                .addGap(106, 106, 106)
                                .addComponent(lblEndDate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgree))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(164, 164, 164)
                                .addComponent(jLabel12)))
                        .addGap(32, 32, 32)
                        .addComponent(btnDeclineContract)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(80, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAViewDetail))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellerClub)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lblBuyerClub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerName)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblWage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblSignOnFee))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblBonus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(lblStartDate)
                    .addComponent(lblEndDate))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgree)
                    .addComponent(btnDeclineContract)
                    .addComponent(jButton1))
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(86, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(407, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreeActionPerformed
        // TODO add your handling code here:
        int row = playerJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        ContractWorkRequest request = (ContractWorkRequest) playerJTable.getValueAt(row, 0);

        UserAccount player = request.getPlayer();
        request.setReceiver(player);
        request.setStatus("Approved");

//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if (organization instanceof PlayerOrganization){
//                org = organization;
//                break;
//            }
//        }
//        if (org!=null){
        player.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Request Submitted!");

//        }
//        Organization org = null;
//        for (Network n : system.getNetworkList()) {
//            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
//                for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
//                    if (organization instanceof PlayerOrganization) {
//                        org = organization;
//                        break;
//                    }
//                }//////////???
//            }
//        }
//
//        if (org != null) {
//            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
//                if (ua.equals(request.getPlayer())) {
//                    ///org.getWorkQueue().getWorkRequestList().add(request);
//                    ua.getWorkQueue().getWorkRequestList().add(request);////?
//                    JOptionPane.showMessageDialog(null, "Request Submitted!");
//                }
//            }
//        }
//        
    }//GEN-LAST:event_btnAgreeActionPerformed

    private void btnDeclineContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineContractActionPerformed
        // TODO add your handling code here:
        int row = playerJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        ContractWorkRequest request = (ContractWorkRequest) playerJTable.getValueAt(row, 0);

        request.setStatus("declined");

//        managerOrganization.getWorkQueue().getWorkRequestList().remove(request);

    }//GEN-LAST:event_btnDeclineContractActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAViewDetailActionPerformed
        // TODO add your handling code here:
        int row = playerJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        ContractWorkRequest request = (ContractWorkRequest) playerJTable.getValueAt(row, 0);

        lblSellerClub.setText(request.getSeller().getName());
        lblBuyerClub.setText(request.getBuyer().getName());
        lblPlayerName.setText(request.getPlayer().getEmployee().getName());
        lblBonus.setText(String.valueOf(request.getBonus()));
        lblSignOnFee.setText(String.valueOf(request.getSignOnFee()));
        lblWage.setText(String.valueOf(request.getWage()));
        lblStartDate.setText(request.getContractStartDate().toString());
        lblEndDate.setText(request.getContractEndDate().toString());
    }//GEN-LAST:event_btnAViewDetailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int row = playerJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        ContractWorkRequest request = (ContractWorkRequest) playerJTable.getValueAt(row, 0);

        UserAccount player = request.getPlayer();

        int signOnFee = request.getSignOnFee();//sign on fee is money that a club can get from the transfer contracts

        Role role = player.getRole();

        if (role instanceof PlayerRole) {
            PlayerRole playerRole = (PlayerRole) role;
            
            Date contractEndDate = playerRole.getLastestContract().getContractEndDate();
            int wage = playerRole.getLastestContract().getWage();
            int earnMoney = 0;
            
            if (contractEndDate.before(new Date())) {//if contract is not end yet
                
                earnMoney = signOnFee - playerRole.getCommercialValue();
                
            }else{//if contract is end                
                Long remainDuration = ((new Date()).getTime()-contractEndDate.getTime());
                Long remainDurationInWeek = remainDuration/(1000*60*60*24*7);
                int remainWeekInt = remainDurationInWeek.intValue();
                earnMoney = signOnFee - playerRole.getCommercialValue() + wage*remainWeekInt;                
            }
            
            if(earnMoney>0){
                JOptionPane.showMessageDialog(null, "This contract can make" + earnMoney +"$", "You Should Agree!", JOptionPane.WARNING_MESSAGE);
            } else if(earnMoney == 0){
                JOptionPane.showMessageDialog(null, "This contract can make" + earnMoney +"$", "You Should Consider Carefully!", JOptionPane.WARNING_MESSAGE);
            }else if(earnMoney < 0){
                JOptionPane.showMessageDialog(null, "This contract can lose" + earnMoney +"$", "You Should Not Agree!!", JOptionPane.WARNING_MESSAGE);
            }
        }                

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAViewDetail;
    private javax.swing.JButton btnAgree;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeclineContract;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblBuyerClub;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblSellerClub;
    private javax.swing.JLabel lblSignOnFee;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblWage;
    private javax.swing.JTable playerJTable;
    // End of variables declaration//GEN-END:variables
}
