/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managerrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.ManagerOrganization;
import business.organization.Organization;
import business.role.PlayerRole;
import business.role.Role;
import business.useraccount.UserAccount;
import business.workqueue.BossToManagerWorkRequest;
import business.workqueue.ContractWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mwhai_000
 */
public class StartTransferContract extends javax.swing.JPanel {

    private UserAccount userAccount;
    private Enterprise enterprise;
    private ManagerOrganization managerOrganization;
    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form CreateContract
     */
    StartTransferContract(JPanel userProcessContainer, UserAccount userAccount, ManagerOrganization managerOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.managerOrganization = managerOrganization;
        this.system = system;

        lblEnterprise.setText(enterprise.getName());
        populatePlayerTable();
        populateEnterpriseComboBox();
    }

    public void populatePlayerTable() {
        DefaultTableModel model = (DefaultTableModel) playerJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : managerOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof BossToManagerWorkRequest) {
                Object[] row = new Object[4];
                row[0] = (BossToManagerWorkRequest) request;
                row[1] = ((BossToManagerWorkRequest) request).getFloorPrice();
                row[2] = ((BossToManagerWorkRequest) request).getCeilingPrice();
                row[3] = ((BossToManagerWorkRequest) request).getTargetPrice();
                model.addRow(row);
            }
        }

    }

    private void populateEnterpriseComboBox() {
        cmbEnterprise.removeAllItems();

        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (!enterprise.equals(this.enterprise)) {
                    cmbEnterprise.addItem(enterprise);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playerJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnStartContract = new javax.swing.JButton();
        btnSendContract = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        cmbEnterprise = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtWage = new javax.swing.JTextField();
        txtSignOnFee = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        playerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Floor Price", "Ceiling Price", "Target Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(playerJTable);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnStartContract.setText("Start A Contract");
        btnStartContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartContractActionPerformed(evt);
            }
        });

        btnSendContract.setText("Send Contract");
        btnSendContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendContractActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Transfer Contract");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Bewteen");

        lblEnterprise.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEnterprise.setText("<Enterprise>");

        cmbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnterpriseActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("and");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Player");

        lblPlayerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPlayerName.setText("<PlayerName>");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Wage:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Transfer Fee:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Start Date:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Bonus:");

        txtWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWageActionPerformed(evt);
            }
        });

        txtSignOnFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignOnFeeActionPerformed(evt);
            }
        });

        txtBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBonusActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel11.setText("Start Transfer Contract");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("End Date:");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("$/Week");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("$");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEnterprise)
                            .addComponent(txtWage)
                            .addComponent(lblPlayerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSignOnFee)
                            .addComponent(txtBonus)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(51, 51, 51)
                                .addComponent(cmbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSendContract))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStartContract))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnStartContract))
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(cmbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerName)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSignOnFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12))
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendContract)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendContractActionPerformed
        // TODO add your handling code here:
        int row = playerJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        BossToManagerWorkRequest request = (BossToManagerWorkRequest) playerJTable.getValueAt(row, 0);
        UserAccount player = request.getPlayer();
        int wage = Integer.parseInt(txtWage.getText());
        int bonus = Integer.parseInt(txtBonus.getText());
        int signOnFee = Integer.parseInt(txtSignOnFee.getText());

        Date startDate = startDateChooser.getDate();
        Date endDate = endDateChooser.getDate();
        Enterprise seller = (Enterprise) cmbEnterprise.getSelectedItem();

        ContractWorkRequest contractRequest = new ContractWorkRequest();

        contractRequest.setPlayer(player);
        contractRequest.setBuyer(enterprise);
        contractRequest.setSeller(seller);
        contractRequest.setBonus(bonus);
        contractRequest.setSignOnFee(signOnFee);
        contractRequest.setWage(wage);
        contractRequest.setSender(userAccount);
        contractRequest.setStatus("Sent");
        contractRequest.setContractStartDate(startDate);
        contractRequest.setContractEndDate(endDate);
        managerOrganization.getWorkQueue().getWorkRequestList().remove(request);

//        for (Organization o : seller.getOrganizationDirectory().getOrganizationList()) {
//            if (o instanceof ManagerOrganization) {
//                o.getWorkQueue().getWorkRequestList().add(request);
//            }
//        }
        Enterprise enp = null;
        Organization org = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.equals(seller)) {
                    enp = enterprise;
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof ManagerOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
///???
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(contractRequest);
        }
        JOptionPane.showMessageDialog(null, "Request Submitted!");

        populatePlayerTable();
    }//GEN-LAST:event_btnSendContractActionPerformed

    private void btnStartContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartContractActionPerformed
        // TODO add your handling code here:
        int row = playerJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        BossToManagerWorkRequest request = (BossToManagerWorkRequest) playerJTable.getValueAt(row, 0);

        UserAccount player = request.getPlayer();
        lblPlayerName.setText(player.getEmployee().getName());


    }//GEN-LAST:event_btnStartContractActionPerformed

    private void txtWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWageActionPerformed

    private void txtSignOnFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignOnFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignOnFeeActionPerformed

    private void txtBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBonusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = playerJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        int earnMoney = 0;

        BossToManagerWorkRequest request = (BossToManagerWorkRequest) playerJTable.getValueAt(row, 0);
        UserAccount player = request.getPlayer();
        int wage = 0;
        int bonus = 0;
        int signOnFee = 0;
                
        try{
            wage = Integer.parseInt(txtWage.getText());
            bonus = Integer.parseInt(txtBonus.getText());
            signOnFee = Integer.parseInt(txtSignOnFee.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Valid!","Warning!",  JOptionPane.WARNING_MESSAGE);
        }

        Date startDate = startDateChooser.getDate();
        Date endDate = endDateChooser.getDate();

        Long duration = startDate.getTime() - endDate.getTime();
        Long durationInWeek = duration / (1000 * 60 * 60 * 24 * 7);
        int durationInWeekInt = durationInWeek.intValue();
        Role role = player.getRole();

        if (role instanceof PlayerRole) {
            PlayerRole playerRole = (PlayerRole) role;
            playerRole.getCommercialValue();

            earnMoney = playerRole.getCommercialValue() - wage * durationInWeekInt - signOnFee - bonus;
            
        }
        if(earnMoney>0){
                JOptionPane.showMessageDialog(null, "This contract can make" + earnMoney +"$", "You Should Agree!", JOptionPane.WARNING_MESSAGE);
        } else if(earnMoney == 0){
                JOptionPane.showMessageDialog(null, "This contract can make" + earnMoney +"$", "You Should Consider Carefully!", JOptionPane.WARNING_MESSAGE);
        }else if(earnMoney < 0){
                JOptionPane.showMessageDialog(null, "This contract can lose" + earnMoney +"$", "You Should Not Agree!!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendContract;
    private javax.swing.JButton btnStartContract;
    private javax.swing.JComboBox cmbEnterprise;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JTable playerJTable;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtSignOnFee;
    private javax.swing.JTextField txtWage;
    // End of variables declaration//GEN-END:variables
}
