/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.playerrole;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.PlayerOrganization;
import business.player.Contract;
import business.role.PlayerRole;
import business.useraccount.UserAccount;
import business.workqueue.ContractWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mwhai_000
 */
public class PlayerSignContractJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private PlayerOrganization playerOrganization;
    private UserAccount account;

    /**
     * Creates new form PlayerWorkAreaJPanel
     */
    public PlayerSignContractJPanel(JPanel userProcessContainer, UserAccount account, PlayerOrganization playerOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.playerOrganization = playerOrganization;

        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSendContract = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSellerClub = new javax.swing.JLabel();
        lblBuyerClub = new javax.swing.JLabel();
        lblWage = new javax.swing.JLabel();
        lblSignOnFee = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSignature = new javax.swing.JTextField();
        refreshTestJButton = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contractRequestJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Bonus:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Wage:");

        btnSendContract.setText("Sign Contract");
        btnSendContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendContractActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Transfer Fee:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Transfer Contract");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Player");

        lblPlayerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPlayerName.setText("<PlayerName>");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("and");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Bewteen");

        lblSellerClub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSellerClub.setText("<Enterprise>");

        lblBuyerClub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBuyerClub.setText("<Enterprise>");

        lblWage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWage.setText("<Wage>");

        lblSignOnFee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSignOnFee.setText("<SignOnFee>");

        lblBonus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBonus.setText("<Bonus>");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Signature:");

        txtSignature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignatureActionPerformed(evt);
            }
        });

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        btnView.setText("View Detail");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDecline.setText("Decline");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        contractRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player Name", "Seller", "Transfer Fee", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(contractRequestJTable);
        if (contractRequestJTable.getColumnModel().getColumnCount() > 0) {
            contractRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            contractRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            contractRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            contractRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Start Date:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("End Date:");

        lblEndDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEndDate.setText("<Duration>");

        lblStartDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblStartDate.setText("<StartDate>");

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("View New Contracts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(btnView)
                            .addGap(221, 221, 221)
                            .addComponent(refreshTestJButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13))
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnBack)
                                        .addGap(62, 62, 62)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnDecline)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSellerClub)
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel5)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(lblBuyerClub))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                                .addComponent(btnSendContract))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPlayerName)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblWage)
                                                .addComponent(lblSignOnFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblBonus)
                                                .addComponent(txtSignature, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblStartDate)
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblEndDate)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(refreshTestJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellerClub)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lblBuyerClub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerName)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblWage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblSignOnFee))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblBonus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(lblStartDate)
                    .addComponent(lblEndDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSignature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendContract)
                    .addComponent(btnDecline)
                    .addComponent(btnBack))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendContractActionPerformed
        // TODO add your handling code here:
        int row = contractRequestJTable.getSelectedRow();
        if (txtSignature.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please sign your name!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ContractWorkRequest request = (ContractWorkRequest) contractRequestJTable.getValueAt(row, 0);

        request.setStatus("Completed");
        enterprise.getEmployeeDirectory().removeEmployee(account.getEmployee());
        enterprise.getUserAccountDirectory().removeUserAccount(account);

        PlayerRole playerRole = (PlayerRole) account.getRole();
        Enterprise buyer = request.getBuyer();
        int cost = request.getSignOnFee();
        int newClubCash = enterprise.getClubCash() + cost;
        int newClubCash2 = buyer.getClubCash() - cost;

        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // yes option

            Contract newContract = playerRole.addContract();
            newContract.setBonus(request.getBonus());
            newContract.setBuyer(buyer);
            newContract.setContractEndDate(request.getContractEndDate());
            newContract.setContractStartDate(request.getContractStartDate());
            newContract.setSeller(request.getSeller());
            newContract.setSignOnFee(cost);
            newContract.setWage(request.getWage());

            enterprise.getSellingContractList().add(newContract);
            buyer.getBuyingContractList().add(newContract);
            
            enterprise.setClubCash(newClubCash);
            buyer.setClubCash(newClubCash2);
            for (Organization o : buyer.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof PlayerOrganization) {
                    o.getUserAccountDirectory().transferUserAccount(account);
                    o.getEmployeeDirectory().transferEmployee(account.getEmployee());
                }
            }

            JOptionPane.showMessageDialog(null, "Transfer Successful!!");
            request.setStatus("Success!");
        }


    }//GEN-LAST:event_btnSendContractActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = contractRequestJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        ContractWorkRequest request = (ContractWorkRequest) contractRequestJTable.getValueAt(row, 0);

        lblSellerClub.setText(request.getSeller().getName());
        lblBuyerClub.setText(request.getBuyer().getName());
        lblPlayerName.setText(account.getEmployee().getName());
        lblBonus.setText(String.valueOf(request.getBonus()));
        lblSignOnFee.setText(String.valueOf(request.getSignOnFee()));
        lblWage.setText(String.valueOf(request.getWage()));
        lblStartDate.setText(request.getContractStartDate().toString());
        lblEndDate.setText(request.getContractEndDate().toString());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        int row = contractRequestJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        ContractWorkRequest request = (ContractWorkRequest) contractRequestJTable.getValueAt(row, 0);

        request.setStatus("Declined");
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSignatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignatureActionPerformed

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) contractRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[4];
            row[0] = request;
            ContractWorkRequest contractRequest = (ContractWorkRequest) request;
            row[1] = contractRequest.getSeller();
            row[2] = contractRequest.getSignOnFee();
            row[3] = contractRequest.getStatus();
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnSendContract;
    private javax.swing.JButton btnView;
    private javax.swing.JTable contractRequestJTable;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblBuyerClub;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblSellerClub;
    private javax.swing.JLabel lblSignOnFee;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblWage;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JTextField txtSignature;
    // End of variables declaration//GEN-END:variables
}
