/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.playerrole;

import business.enterprise.Enterprise;
import business.organization.PlayerOrganization;
import business.player.Contract;
import business.role.PlayerRole;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mwhai_000
 */
public class ViewContractHistoryJPanel extends javax.swing.JPanel {

    private  UserAccount account;
    private  Enterprise enterprise;
    private  PlayerOrganization playerOrganization;
    private  JPanel userProcessContainer;

    /**
     * Creates new form ViewContractJPanel
     */

    ViewContractHistoryJPanel(JPanel userProcessContainer, UserAccount account, PlayerOrganization playerOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.playerOrganization = playerOrganization;
        populateTable();
    } 
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblContract.getModel();
        PlayerRole playerRole = (PlayerRole)account.getRole();
        model.setRowCount(0);
        for (Contract c : playerRole.getContractList()){
            Object[] row = new Object[3];
            row[0] = c;       
            row[1] = c.getContractEndDate().toString();
            row[2] = c.getSignOnFee();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblContract = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSellerClub = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblBuyerClub = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblWage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblSignOnFee = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();

        tblContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player Name", "Due To", "Transfer Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContract);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Transfer Fee:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Transfer Contract");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Player");

        lblPlayerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPlayerName.setText("<PlayerName>");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("and");

        lblEndDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEndDate.setText("<Duration>");

        lblStartDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblStartDate.setText("<StartDate>");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Bewteen");

        lblSellerClub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSellerClub.setText("<Enterprise>");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Start Date:");

        lblBuyerClub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBuyerClub.setText("<Enterprise>");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("End Date:");

        lblWage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWage.setText("<Wage>");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Bonus:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Wage:");

        btnView.setText("View Detail");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblSignOnFee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSignOnFee.setText("<SignOnFee>");

        lblBonus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBonus.setText("<Bonus>");

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("View Previous Contract");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13))
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnBack)
                                        .addGap(62, 62, 62)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSellerClub)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel5)
                                        .addGap(40, 40, 40)
                                        .addComponent(lblBuyerClub))
                                    .addComponent(lblPlayerName)
                                    .addComponent(lblWage)
                                    .addComponent(lblSignOnFee)
                                    .addComponent(lblBonus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStartDate)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEndDate))))
                            .addComponent(btnView)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellerClub)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lblBuyerClub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerName)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblWage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblSignOnFee))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblBonus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(lblStartDate)
                    .addComponent(lblEndDate))
                .addGap(63, 63, 63)
                .addComponent(btnBack)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = tblContract.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        Contract contract = (Contract) tblContract.getValueAt(row, 0);

        lblSellerClub.setText(contract.getSeller().getName());
        lblBuyerClub.setText(contract.getBuyer().getName());
        lblPlayerName.setText(account.getEmployee().getName());
        lblBonus.setText(String.valueOf(contract.getBonus()));
        lblSignOnFee.setText(String.valueOf(contract.getSignOnFee()));
        lblWage.setText(String.valueOf(contract.getWage()));
        lblStartDate.setText(contract.getContractStartDate().toString());
        lblEndDate.setText(contract.getContractEndDate().toString());
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblBuyerClub;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblSellerClub;
    private javax.swing.JLabel lblSignOnFee;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblWage;
    private javax.swing.JTable tblContract;
    // End of variables declaration//GEN-END:variables
}
