/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.bossrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.BossOrganization;
import business.role.PlayerRole;
import business.useraccount.UserAccount;
import business.workqueue.BossToManagerWorkRequest;
import business.workqueue.ReportWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leslie
 */
public class PlayersToBuyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private BossOrganization bossOrganization;
    private EcoSystem system;

    PlayersToBuyJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, BossOrganization organization, EcoSystem system) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.bossOrganization = organization;
        this.system = system;
        populatePlayerTable();
        populateSetPriceHistoryTable();
    }

    public void populatePlayerTable() {
        DefaultTableModel model = (DefaultTableModel) playersToBuyTbl.getModel();

        model.setRowCount(0);
        
        for (WorkRequest request : bossOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ReportWorkRequest) {
                UserAccount player = ((ReportWorkRequest)request).getPlayer();
                PlayerRole playerRole = (PlayerRole)player.getRole();
                Object[] row = new Object[4];
                row[0] = (ReportWorkRequest) request;
                row[1] = playerRole.getCurrentClubName();
                row[2] = playerRole.getPosition();
                row[3] = playerRole.getCommercialValue();
                model.addRow(row);
            }
        }

    }
    
    public void populateSetPriceHistoryTable() {
        DefaultTableModel model = (DefaultTableModel) setPriceHistoryTbl.getModel();

        model.setRowCount(0);
        
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            if (request instanceof BossToManagerWorkRequest) {
                BossToManagerWorkRequest bossToManagerWorkRequest= (BossToManagerWorkRequest)request;
                UserAccount player = bossToManagerWorkRequest.getPlayer();
               
                Object[] row = new Object[4];
                row[0] = player.getEmployee();
                row[1] = bossToManagerWorkRequest.getCeilingPrice();
                row[2] = bossToManagerWorkRequest.getFloorPrice();
                row[3] = bossToManagerWorkRequest.getTargetPrice();
                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playersToBuyTbl = new javax.swing.JTable();
        setPriceBtn = new javax.swing.JButton();
        detailBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        setPriceHistoryTbl = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        lblDefence = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblPhysical = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPostion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblCommercialValue = new javax.swing.JLabel();
        lblClub = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDribble = new javax.swing.JLabel();
        lblShoot = new javax.swing.JLabel();

        jLabel1.setText("Players to buy (from manager)");

        playersToBuyTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Club", "Position", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(playersToBuyTbl);
        if (playersToBuyTbl.getColumnModel().getColumnCount() > 0) {
            playersToBuyTbl.getColumnModel().getColumn(0).setMinWidth(2);
        }

        setPriceBtn.setText("Set Price");
        setPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPriceBtnActionPerformed(evt);
            }
        });

        detailBtn.setText("See Detail");
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Set price history");

        setPriceHistoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Ceiling Price", "Floor Price", "Target Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(setPriceHistoryTbl);
        if (setPriceHistoryTbl.getColumnModel().getColumnCount() > 0) {
            setPriceHistoryTbl.getColumnModel().getColumn(0).setMinWidth(2);
        }

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        lblDefence.setText("<Value>");

        lblSpeed.setText("<Value>");

        lblPass.setText("<Value>");

        lblPhysical.setText("<Value>");

        lblName.setText("<Value>");

        lblPostion.setText("<Value>");

        jLabel7.setText("Position:");

        jLabel8.setText("Age:");

        jLabel9.setText("Name:");

        jLabel10.setText("Country:");

        lblCountry.setText("<Value>");

        lblCommercialValue.setText("<Value>");

        lblClub.setText("<Value>");

        lblAge.setText("<Value>");

        jLabel6.setText("Physical:");

        jLabel11.setText("Commercial Value");

        jLabel5.setText("Pass:");

        jLabel12.setText("Club:");

        jLabel4.setText("Speed:");

        jLabel3.setText("Defence:");

        jLabel13.setText("Shoot:");

        jLabel14.setText("Dribble:");

        lblDribble.setText("<Value>");

        lblShoot.setText("<Value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(backBtn)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(detailBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setPriceBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblPostion)
                                    .addComponent(lblAge)
                                    .addComponent(lblCountry)
                                    .addComponent(lblClub)
                                    .addComponent(lblCommercialValue))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDribble)
                                    .addComponent(lblShoot)
                                    .addComponent(lblDefence)
                                    .addComponent(lblSpeed)
                                    .addComponent(lblPass)
                                    .addComponent(lblPhysical))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setPriceBtn)
                    .addComponent(detailBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblDribble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblShoot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblDefence))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhysical)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblPostion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblCountry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblClub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCommercialValue))))
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(backBtn)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        int selectedRow = playersToBuyTbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            
        } else {
            ReportWorkRequest reportWorkRequest = (ReportWorkRequest) playersToBuyTbl.getValueAt(selectedRow, 0);
            UserAccount player = reportWorkRequest.getPlayer();

//            Player p = reportWorkRequest.getPlayerPerson();
//            
//            lblName.setText(player.getEmployee().getName());
//            lblPostion.setText(p.getPosition());
//            lblClub.setText(p.getCurrentClubName());
//            lblAge.setText(p.getBirthDate().toString());
//            lblCountry.setText(p.getNationality());
//            lblCommercialValue.setText("$" + p.getCommercialValue() + "million");
//            lblDribble.setText(String.valueOf(reportWorkRequest.getDribbble()));
//            lblDefence.setText(String.valueOf(reportWorkRequest.getDefence()));
//            lblPass.setText(String.valueOf(reportWorkRequest.getPassing()));
//            lblShoot.setText(String.valueOf(reportWorkRequest.getShoot()));
//            lblSpeed.setText(String.valueOf(reportWorkRequest.getSpeed()));
//            lblPhysical.setText(String.valueOf(reportWorkRequest.getPhysical()));
            
            PlayerRole p = (PlayerRole)player.getRole();
            
            lblName.setText(player.getEmployee().getName());
            lblPostion.setText(p.getPosition());
            lblClub.setText(p.getCurrentClubName());
            lblAge.setText(String.valueOf(p.getAge()));
            lblCountry.setText(p.getNationality());
            lblCommercialValue.setText("$" + p.getCommercialValue() + "million");
            lblDribble.setText(String.valueOf(reportWorkRequest.getDribbble()));
            lblDefence.setText(String.valueOf(reportWorkRequest.getDefence()));
            lblPass.setText(String.valueOf(reportWorkRequest.getPassing()));
            lblShoot.setText(String.valueOf(reportWorkRequest.getShoot()));
            lblSpeed.setText(String.valueOf(reportWorkRequest.getSpeed()));
            lblPhysical.setText(String.valueOf(reportWorkRequest.getPhysical()));
        }
    }//GEN-LAST:event_detailBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void setPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPriceBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = playersToBuyTbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            
        } else {
            ReportWorkRequest reportWorkRequest = (ReportWorkRequest) playersToBuyTbl.getValueAt(selectedRow, 0);
            reportWorkRequest.setStatus("Completed");
            UserAccount player = reportWorkRequest.getPlayer();
            
        SetPriceJPanel setPriceJPane = new SetPriceJPanel(userProcessContainer, account, bossOrganization, enterprise, player);
        userProcessContainer.add("setPriceJPane", setPriceJPane);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_setPriceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton detailBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblClub;
    private javax.swing.JLabel lblCommercialValue;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDefence;
    private javax.swing.JLabel lblDribble;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhysical;
    private javax.swing.JLabel lblPostion;
    private javax.swing.JLabel lblShoot;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JTable playersToBuyTbl;
    private javax.swing.JButton setPriceBtn;
    private javax.swing.JTable setPriceHistoryTbl;
    // End of variables declaration//GEN-END:variables
}
