/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.bossrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.BossOrganization;
import business.organization.ManagerOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.BossToManagerWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author leslie
 */
public class SetPriceJPanel extends javax.swing.JPanel {

    private  JPanel userProcessContainer;
    private  UserAccount account;

    private  UserAccount player;
    private  Enterprise enterprise;
    private  BossOrganization organization;

    /**
     * Creates new form SetPriceJPanel
     */

    SetPriceJPanel(JPanel userProcessContainer, UserAccount account, BossOrganization organization, Enterprise enterprise, UserAccount player) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.organization = organization;
        this.player = player;
        lblClubCash.setText(String.valueOf(enterprise.getClubCash()));
        lblClubCash1.setText(TOOL_TIP_TEXT_KEY);
        
    }
    public boolean isNumber(String str){
        boolean isNum =false;
        for (int i = str.length();--i>=0;){  
            if (!Character.isDigit(str.charAt(i))){
            isNum = false;
            break;
            }
        isNum = true;
        }
        if (isNum) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Please fill a number less than 5");
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ceilingPriceTextField = new javax.swing.JTextField();
        floorPriceTextField = new javax.swing.JTextField();
        targetPriceTextField = new javax.swing.JTextField();
        setBtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        lblClubCash = new javax.swing.JLabel();
        enterpriseLabel4 = new javax.swing.JLabel();
        enterpriseLabel7 = new javax.swing.JLabel();
        enterpriseLabel8 = new javax.swing.JLabel();
        lblClubCash1 = new javax.swing.JLabel();
        lblClubCash2 = new javax.swing.JLabel();

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Set Price");

        jLabel2.setText("Ceiling Price:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setText("Floor Price:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setText("Target Price:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        ceilingPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceilingPriceTextFieldActionPerformed(evt);
            }
        });

        floorPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorPriceTextFieldActionPerformed(evt);
            }
        });

        targetPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetPriceTextFieldActionPerformed(evt);
            }
        });

        setBtn.setText("Set");
        setBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBtnActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel.setText("The highest valueof this player is:");

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel1.setText("Club cash now is:");

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel2.setText("The lowest value of this player is:");

        lblClubCash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClubCash.setText("<value>");

        enterpriseLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel4.setText("million $");

        enterpriseLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel7.setText("million $");

        enterpriseLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel8.setText("million $");

        lblClubCash1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClubCash1.setText("<value>");

        lblClubCash2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClubCash2.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClubCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enterpriseLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblClubCash2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(enterpriseLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblClubCash1)))
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseLabel7)
                            .addComponent(enterpriseLabel8)
                            .addComponent(enterpriseLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ceilingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floorPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(targetPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(94, 94, 94)
                                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClubCash)
                    .addComponent(enterpriseLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel7)
                    .addComponent(lblClubCash1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel8)
                    .addComponent(lblClubCash2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ceilingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(floorPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(targetPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(setBtn))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ceilingPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceilingPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceilingPriceTextFieldActionPerformed

    private void floorPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorPriceTextFieldActionPerformed

    private void targetPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetPriceTextFieldActionPerformed

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBtnActionPerformed
        // TODO add your handling code here:
        BossToManagerWorkRequest bossToManagerWorkRequest = new BossToManagerWorkRequest();        
        try{
            int ceiling = Integer.parseInt(ceilingPriceTextField.getText());
             int floor = Integer.parseInt(floorPriceTextField.getText());
             int target = Integer.parseInt(targetPriceTextField.getText());
                        
        
            bossToManagerWorkRequest.setPlayer(player);
            bossToManagerWorkRequest.setCeilingPrice(ceiling);
            bossToManagerWorkRequest.setFloorPrice(floor);
            bossToManagerWorkRequest.setTargetPrice(target);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Valid Price");
        }
        
        bossToManagerWorkRequest.setSender(account);
        bossToManagerWorkRequest.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ManagerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(bossToManagerWorkRequest);
            account.getWorkQueue().getWorkRequestList().add(bossToManagerWorkRequest);
            
            JOptionPane.showMessageDialog(null, "Request Submit Successful!!");

        }
        
    }//GEN-LAST:event_setBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:userProcessContainer.remove(this);
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PlayersToBuyJPanel pybjp = (PlayersToBuyJPanel) component;
        pybjp.populatePlayerTable();
        pybjp.populateSetPriceHistoryTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField ceilingPriceTextField;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel enterpriseLabel4;
    private javax.swing.JLabel enterpriseLabel7;
    private javax.swing.JLabel enterpriseLabel8;
    private javax.swing.JTextField floorPriceTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblClubCash;
    private javax.swing.JLabel lblClubCash1;
    private javax.swing.JLabel lblClubCash2;
    private javax.swing.JButton setBtn;
    private javax.swing.JTextField targetPriceTextField;
    // End of variables declaration//GEN-END:variables
}
